export const Players = [
  {
    id: 1,
    name: 'Star Wars - Episode 1',
    year: '1999',
    nation: 'USA',
    img: 'assets/images/StarWars1.jpg',
    info: 'Chiến tranh giữa các vì sao: Tập I – Hiểm họa bóng ma là một bộ phim sử thi không gian của Mỹ năm 1999 được biên kịch và đạo diễn bởi George Lucas, sản xuất bởi Lucasfilm và phân phối bởi 20th Century Fox.'
  },
  {
    id: 2,
    name: 'Star Wars - Episode 2',
    year: '2002',
    nation: 'USA',
    img: 'assets/images/StarWars2.jpg',
    info: 'Star Wars Episode II: Attack of the Clones với tên tiếng Việt là Chiến tranh giữa các vì sao: Cuộc tấn công của người Vô tính là phần 2 của loạt phim Chiến tranh giữa các vì sao, ra mắt khán giả năm 2002.'
  },
  { id: 3, 
    name: 'Star Wars - Episode 3', 
    year: '2005', 
    nation: 'USA',
    img: 'assets/images/StarWars3.jpg',
    info: 'Chiến tranh giữa các vì sao: Tập III – Sự báo thù của người Sith là một bộ phim không gian sử thi của Mỹ năm 2005 do George Lucas viết kịch bản và đạo diễn' },
  { id: 4, 
    name: 'Star Wars - Episode 4', 
    year: '1977', 
    nation: 'USA',
    img: 'assets/images/StarWars4.jpg',
    info: 'Chiến tranh giữa các vì sao: Tập 4 – Niềm hi vọng mới là phim điện ảnh sử thi không gian của Mỹ công chiếu năm 1977 do George Lucas làm đạo diễn kiêm biên kịch. Đây là bộ phim đầu tiên trong bộ ba tác phẩm gốc và là bộ phim đầu tiên của nhượng quyền Star Wars.' },
  { id: 5, 
    name: 'Star Wars - Episode 5',
    year: '1980', 
    nation: 'USA',
    img: 'assets/images/StarWars5.jpg',
    info: 'Đế chế phản công, còn được gọi là Chiến tranh giữa các vì sao: Tập V – Đế chế phản công, là một bộ phim sử thi opera không gian Mỹ năm 1980 của đạo diễn Irvin Kershner và được biên kịch bởi Leigh Brackett và Lawrence Kasdan, dựa trên câu chuyện của George Lucas.'},
  { id: 6, 
    name: 'Star Wars - Episode 6', 
    year: '1983', 
    nation: 'USA',
    img: 'assets/images/StarWars6.jpg',
    info: 'Sự trở lại của Jedi, hay được viết đến với tên gọi Chiến tranh giữa các vì sao: Tập VI – Sự trở lại của Jedi là một bộ phim kinh kịch vũ trụ sử thi của Mỹ năm 1983 do Richard Marquand đạo diễn. Kịch bản của Lawrence Kasdan và George Lucas từ một câu chuyện của Lucas, người cũng là giám đốc sản xuất.' },
  { id: 7, 
    name: 'Star Wars - Episode 7', 
    year: '2015', 
    nation: 'USA',
    img: 'assets/images/StarWars7.jpg',
    info: 'Star Wars: Thần lực thức tỉnh là một bộ phim điện ảnh thuộc thể loại sử thi không gian của Mỹ năm 2015 do J. J. Abrams làm đạo diễn, viết kịch bản và đồng sản xuất.' },
  { id: 8, 
    name: 'Star Wars - Episode 8', 
    year: '2017', 
    nation: 'USA',
    img: 'assets/images/StarWars8.jpg',
    info: 'Star Wars: Jedi cuối cùng là phim điện ảnh sử thi không gian của Mỹ năm 2017 do Rian Johnson chịu trách nhiệm đạo diễn kiêm biên kịch.' },
  { id: 9, 
    name: 'Star Wars - Episode 9', 
    year: '2019', 
    nation: 'USA',
    img: 'assets/images/StarWars9.jpg',
    info: 'Star Wars: Skywalker trỗi dậy là một bộ phim điện ảnh sử thi không gian Mỹ năm 2019, được sản xuất, đồng sáng tác và đạo diễn bởi J. J. Abrams.' }
];
export default Players;